server:
  port: ${PORT}
  external-port: ${EXTERNAL_PORT}
  protocol: ${PROTOCOL}
  domain: ${DOMAIN}

spring:
  application:
    name: word-online-server
  config:
    import: optional:file:.env[.properties]
  sql:
    init:
      schema-locations: classpath:static/sql/schema.sql
      data-locations: classpath:static/sql/data.sql
      mode: embedded
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PW}

logging:
  discord-webhook-url: ${DISCORD_WEBHOOK_URL}
  level:
    org.springframework.web.socket: WARN
    org.springframework.messaging: WARN

team6515:
  server:
    account:
      url: ${ACCOUNT_SERVER_URL}

jwt:
  public:
    key: ${JWT_PUBLIC_KEY}